"""Build content/decks/german-a1.csv.

Word selection: the FrequencyWords German list (hermitdave/FrequencyWords,
2018, from OpenSubtitles, CC BY-SA 4.0), walked in frequency order, inflected
forms folded into one lemma, function words, names, interjections and
vulgarities dropped, until 300 content words. A further 28 were dropped by
hand from the 328 that pass the filter: crime-drama vocabulary that subtitles
overweight (Waffe, Blut, Krieg, Gefängnis, Opfer, König, Tod, Schatz, Typ,
Kumpel), colloquial particles (raus, runter), and abstract or B1-level items
(Schiff, Menge, Wert, eher, völlig, Stelle, Rest, damals, nachdem, bereits,
Wahl, Art, fest, Wagen, sogar, Ruhe). The rank column is the lemma's
most frequent form's rank in that list. English glosses and example sentences
are original. Output is CC BY-SA 4.0.

Run: python3 content/decks/build_german_a1.py
"""

import csv
from pathlib import Path

# (rank, front, back, example, note)
CARDS = [
    (51, "können", "can, to be able to", "Ich kann heute nicht kommen.", "I cannot come today. ich kann, du kannst, er kann"),
    (52, "gut", "good, well", "Das Essen ist sehr gut.", "The food is very good."),
    (56, "sein", "to be", "Wir sind zu Hause.", "We are at home. ich bin, du bist, er ist, wir sind"),
    (79, "wollen", "to want", "Ich will ein Eis.", "I want an ice cream. ich will, du willst, er will"),
    (89, "immer", "always", "Er ist immer müde.", "He is always tired."),
    (91, "warum", "why", "Warum lachst du?", "Why are you laughing?"),
    (92, "vor", "in front of, before", "Das Auto steht vor dem Haus.", "The car is in front of the house."),
    (94, "wieder", "again", "Bis morgen, wir sehen uns wieder.", "See you tomorrow, we will see each other again."),
    (96, "sagen", "to say", "Was sagst du?", "What are you saying?"),
    (97, "machen", "to make, to do", "Was machst du heute?", "What are you doing today?"),
    (98, "danke", "thank you", "Danke für das Buch.", "Thank you for the book."),
    (99, "sehr", "very", "Das Wasser ist sehr kalt.", "The water is very cold."),
    (100, "alle", "all, everyone", "Alle sind hier.", "Everyone is here."),
    (102, "der Mann", "the man", "Der Mann liest die Zeitung.", "The man is reading the newspaper. Plural: die Männer"),
    (103, "tun", "to do", "Ich habe viel zu tun.", "I have a lot to do."),
    (106, "gehen", "to go, to walk", "Wir gehen in die Stadt.", "We are going into town."),
    (107, "sehen", "to see", "Ich sehe einen Hund.", "I see a dog. du siehst, er sieht"),
    (108, "vielleicht", "maybe", "Vielleicht regnet es morgen.", "Maybe it will rain tomorrow."),
    (116, "über", "over, about", "Wir sprechen über den Film.", "We are talking about the film."),
    (117, "es gibt", "there is, there are", "Es gibt hier keinen Bus.", "There is no bus here."),
    (119, "wissen", "to know (a fact)", "Ich weiß es nicht.", "I do not know. ich weiß, du weißt, er weiß"),
    (124, "nie", "never", "Ich trinke nie Kaffee.", "I never drink coffee."),
    (125, "wirklich", "really", "Ist das wirklich dein Auto?", "Is that really your car?"),
    (134, "einfach", "simple, simply", "Die Aufgabe ist einfach.", "The task is simple."),
    (135, "das Leben", "the life", "Das Leben in Berlin ist teuer.", "Life in Berlin is expensive."),
    (137, "die Zeit", "the time", "Ich habe keine Zeit.", "I have no time."),
    (140, "kommen", "to come", "Kommst du mit?", "Are you coming along?"),
    (142, "heute", "today", "Heute ist Montag.", "Today is Monday."),
    (151, "sicher", "sure, safe", "Bist du sicher?", "Are you sure?"),
    (153, "die Frau", "the woman, the wife", "Die Frau arbeitet im Büro.", "The woman works in the office. Plural: die Frauen"),
    (157, "leid tun", "to be sorry", "Es tut mir leid.", "I am sorry."),
    (162, "zurück", "back", "Ich komme um acht zurück.", "I will come back at eight."),
    (163, "lassen", "to let, to leave", "Lass mich in Ruhe.", "Leave me alone. du lässt, er lässt"),
    (164, "hallo", "hello", "Hallo, wie geht es dir?", "Hello, how are you?"),
    (169, "zwei", "two", "Ich habe zwei Brüder.", "I have two brothers."),
    (171, "genau", "exactly", "Das ist genau richtig.", "That is exactly right."),
    (176, "morgen", "tomorrow", "Morgen habe ich frei.", "Tomorrow I have the day off. Der Morgen: the morning"),
    (177, "die Leute", "the people", "Die Leute warten auf den Bus.", "The people are waiting for the bus. Plural only"),
    (178, "der Vater", "the father", "Mein Vater kocht gern.", "My father likes to cook. Plural: die Väter"),
    (179, "schön", "beautiful, nice", "Das Wetter ist schön.", "The weather is nice."),
    (183, "gerade", "right now, just", "Ich esse gerade.", "I am eating right now."),
    (184, "der Tag", "the day", "Der Tag ist lang.", "The day is long. Plural: die Tage"),
    (186, "reden", "to talk", "Wir reden über die Arbeit.", "We are talking about work."),
    (188, "lieben", "to love", "Ich liebe Musik.", "I love music."),
    (192, "jemand", "someone", "Jemand klopft an die Tür.", "Someone is knocking at the door."),
    (193, "das Geld", "the money", "Ich habe kein Geld dabei.", "I have no money with me."),
    (194, "durch", "through", "Wir gehen durch den Park.", "We walk through the park."),
    (197, "die Mutter", "the mother", "Meine Mutter ist Ärztin.", "My mother is a doctor. Plural: die Mütter"),
    (204, "besser", "better", "Heute geht es mir besser.", "I feel better today."),
    (211, "möchten", "would like", "Ich möchte einen Tee.", "I would like a tea. ich möchte, du möchtest"),
    (218, "helfen", "to help", "Kannst du mir helfen?", "Can you help me? du hilfst, er hilft"),
    (219, "die Nacht", "the night", "Die Nacht ist kalt.", "The night is cold. Plural: die Nächte"),
    (220, "finden", "to find", "Ich finde meinen Schlüssel nicht.", "I cannot find my key."),
    (224, "lange", "for a long time", "Wir warten schon lange.", "We have been waiting for a long time."),
    (225, "natürlich", "of course, natural", "Natürlich komme ich.", "Of course I am coming."),
    (228, "gar nicht", "not at all", "Das ist gar nicht schwer.", "That is not hard at all."),
    (232, "weiter", "further, on", "Wir gehen weiter.", "We keep going."),
    (233, "geben", "to give", "Gib mir bitte das Salz.", "Please give me the salt. du gibst, er gibt"),
    (235, "gleich", "right away, same", "Ich komme gleich.", "I am coming right away."),
    (237, "recht haben", "to be right", "Du hast recht.", "You are right."),
    (239, "richtig", "right, correct", "Die Antwort ist richtig.", "The answer is correct."),
    (240, "in Ordnung", "all right, okay", "Alles in Ordnung?", "Everything all right?"),
    (242, "hören", "to hear, to listen", "Ich höre Musik.", "I am listening to music."),
    (249, "zu Hause", "at home", "Ich bleibe heute zu Hause.", "I am staying at home today. nach Hause: (going) home"),
    (251, "das Mädchen", "the girl", "Das Mädchen spielt im Garten.", "The girl is playing in the garden. Plural: die Mädchen"),
    (254, "der Abend", "the evening", "Am Abend lese ich.", "In the evening I read. Plural: die Abende"),
    (255, "das Haus", "the house", "Das Haus ist alt.", "The house is old. Plural: die Häuser"),
    (257, "viel", "much, a lot", "Er arbeitet viel.", "He works a lot. viele: many"),
    (258, "drei", "three", "Der Kurs dauert drei Wochen.", "The course lasts three weeks."),
    (260, "der Freund", "the friend, the boyfriend", "Mein Freund wohnt in Köln.", "My friend lives in Cologne. Plural: die Freunde"),
    (265, "der Mensch", "the human, the person", "Viele Menschen mögen Kaffee.", "Many people like coffee. Plural: die Menschen"),
    (266, "essen", "to eat", "Wir essen um sieben.", "We eat at seven. du isst, er isst"),
    (267, "die Angst", "the fear", "Ich habe Angst vor Hunden.", "I am afraid of dogs. Plural: die Ängste"),
    (268, "bleiben", "to stay", "Bleib hier.", "Stay here."),
    (269, "zusammen", "together", "Wir lernen zusammen.", "We study together."),
    (270, "die Welt", "the world", "Die Welt ist groß.", "The world is big."),
    (271, "unter", "under, among", "Die Katze liegt unter dem Tisch.", "The cat is lying under the table."),
    (273, "schnell", "fast, quick", "Das Auto ist schnell.", "The car is fast."),
    (275, "tot", "dead", "Die Pflanze ist tot.", "The plant is dead."),
    (280, "stimmen", "to be correct", "Das stimmt.", "That is right."),
    (281, "nehmen", "to take", "Ich nehme den Bus.", "I take the bus. du nimmst, er nimmt"),
    (282, "das Kind", "the child", "Das Kind schläft.", "The child is sleeping. Plural: die Kinder"),
    (284, "glauben", "to believe, to think", "Ich glaube, es regnet.", "I think it is raining."),
    (285, "bringen", "to bring", "Bring bitte Brot mit.", "Please bring bread."),
    (286, "ganz", "whole, quite", "Ich habe den ganzen Tag gearbeitet.", "I worked the whole day."),
    (287, "genug", "enough", "Wir haben genug Zeit.", "We have enough time."),
    (289, "brauchen", "to need", "Ich brauche eine Pause.", "I need a break."),
    (291, "der Moment", "the moment", "Einen Moment, bitte.", "One moment, please. Plural: die Momente"),
    (292, "der Junge", "the boy", "Der Junge spielt Fußball.", "The boy plays football. Plural: die Jungen"),
    (295, "die Musik", "the music", "Ich mag laute Musik.", "I like loud music."),
    (296, "die Arbeit", "the work, the job", "Die Arbeit beginnt um neun.", "Work starts at nine."),
    (299, "fragen", "to ask", "Frag den Lehrer.", "Ask the teacher."),
    (300, "der Herr", "the gentleman, Mr", "Guten Tag, Herr Müller.", "Good day, Mr Müller. Plural: die Herren"),
    (302, "heißen", "to be called", "Ich heiße Anna.", "My name is Anna. du heißt, er heißt"),
    (303, "die Familie", "the family", "Meine Familie ist groß.", "My family is big. Plural: die Familien"),
    (304, "warten", "to wait", "Wir warten auf den Zug.", "We are waiting for the train."),
    (305, "niemand", "nobody", "Niemand ist zu Hause.", "Nobody is at home."),
    (306, "sofort", "immediately", "Komm sofort her.", "Come here immediately."),
    (307, "bevor", "before", "Wasch die Hände, bevor du isst.", "Wash your hands before you eat."),
    (308, "das Jahr", "the year", "Das Jahr hat zwölf Monate.", "The year has twelve months. Plural: die Jahre"),
    (309, "einmal", "once", "Ich war einmal in Wien.", "I was in Vienna once."),
    (310, "das Problem", "the problem", "Das ist kein Problem.", "That is no problem. Plural: die Probleme"),
    (311, "der Sohn", "the son", "Ihr Sohn ist zehn Jahre alt.", "Her son is ten years old. Plural: die Söhne"),
    (312, "wann", "when", "Wann kommt der Bus?", "When does the bus come?"),
    (314, "fertig", "finished, ready", "Bist du fertig?", "Are you finished?"),
    (318, "sprechen", "to speak", "Sprechen Sie Deutsch?", "Do you speak German? du sprichst, er spricht"),
    (319, "beide", "both", "Beide Kinder sind müde.", "Both children are tired."),
    (323, "die Hilfe", "the help", "Danke für deine Hilfe.", "Thanks for your help."),
    (331, "halten", "to hold, to stop", "Halt die Tasche fest.", "Hold the bag tight. du hältst, er hält"),
    (338, "wahr", "true", "Das ist nicht wahr.", "That is not true."),
    (341, "der Bruder", "the brother", "Mein Bruder ist älter als ich.", "My brother is older than me. Plural: die Brüder"),
    (344, "denken", "to think", "Ich denke an dich.", "I am thinking of you."),
    (348, "lieber", "rather, preferably", "Ich trinke lieber Tee.", "I would rather drink tea."),
    (355, "vergessen", "to forget", "Vergiss den Schlüssel nicht.", "Do not forget the key. du vergisst, er vergisst"),
    (356, "die Frage", "the question", "Ich habe eine Frage.", "I have a question. Plural: die Fragen"),
    (368, "die Uhr", "the clock, o'clock", "Es ist drei Uhr.", "It is three o'clock. Plural: die Uhren"),
    (369, "die Stadt", "the city, the town", "Die Stadt ist laut.", "The city is loud. Plural: die Städte"),
    (371, "das Baby", "the baby", "Das Baby weint.", "The baby is crying. Plural: die Babys"),
    (372, "fahren", "to drive, to ride, to go (by vehicle)", "Wir fahren nach Hamburg.", "We are going to Hamburg. du fährst, er fährt"),
    (373, "der Name", "the name", "Wie ist Ihr Name?", "What is your name? Plural: die Namen"),
    (374, "bekommen", "to get, to receive", "Ich bekomme ein Paket.", "I am getting a parcel."),
    (375, "der Kopf", "the head", "Mein Kopf tut weh.", "My head hurts. Plural: die Köpfe"),
    (378, "klein", "small", "Die Wohnung ist klein.", "The flat is small."),
    (379, "später", "later", "Wir essen später.", "We will eat later."),
    (380, "das Glück", "the luck, the happiness", "Viel Glück!", "Good luck!"),
    (381, "letzte", "last", "Das ist die letzte Frage.", "That is the last question."),
    (386, "das Ende", "the end", "Das Ende des Films ist traurig.", "The end of the film is sad."),
    (388, "bald", "soon", "Bis bald!", "See you soon!"),
    (390, "das Ding", "the thing", "Was ist das für ein Ding?", "What kind of thing is that? Plural: die Dinge"),
    (392, "toll", "great", "Das Konzert war toll.", "The concert was great."),
    (394, "die Minute", "the minute", "Der Bus kommt in fünf Minuten.", "The bus comes in five minutes. Plural: die Minuten"),
    (396, "bereit", "ready", "Ich bin bereit.", "I am ready."),
    (397, "weit", "far", "Der Bahnhof ist nicht weit.", "The station is not far."),
    (398, "die Ahnung", "the idea, the clue", "Ich habe keine Ahnung.", "I have no idea."),
    (400, "ein bisschen", "a little", "Ich spreche ein bisschen Deutsch.", "I speak a little German."),
    (401, "die Tür", "the door", "Die Tür ist offen.", "The door is open. Plural: die Türen"),
    (402, "das Auto", "the car", "Das Auto ist neu.", "The car is new. Plural: die Autos"),
    (405, "das Auge", "the eye", "Sie hat blaue Augen.", "She has blue eyes. Plural: die Augen"),
    (406, "die Polizei", "the police", "Ruf die Polizei!", "Call the police!"),
    (407, "stehen", "to stand", "Der Tisch steht am Fenster.", "The table stands by the window."),
    (408, "sterben", "to die", "Die Blumen sterben ohne Wasser.", "The flowers die without water. er stirbt"),
    (410, "draußen", "outside", "Draußen ist es kalt.", "It is cold outside."),
    (414, "vorbei", "over, past", "Der Winter ist vorbei.", "The winter is over."),
    (415, "treffen", "to meet", "Wir treffen uns um sechs.", "We meet at six. du triffst, er trifft"),
    (416, "gern", "gladly, like to", "Ich lese gern.", "I like to read."),
    (419, "arbeiten", "to work", "Sie arbeitet in einer Bank.", "She works in a bank."),
    (421, "verrückt", "crazy", "Das ist eine verrückte Idee.", "That is a crazy idea."),
    (422, "neu", "new", "Ich habe ein neues Handy.", "I have a new phone."),
    (424, "hinter", "behind", "Der Garten ist hinter dem Haus.", "The garden is behind the house."),
    (425, "die Sorge", "the worry", "Mach dir keine Sorgen.", "Do not worry. Plural: die Sorgen"),
    (426, "einzig", "only, single", "Das ist mein einziges Hemd.", "That is my only shirt."),
    (429, "die Tochter", "the daughter", "Ihre Tochter studiert.", "Her daughter is at university. Plural: die Töchter"),
    (431, "die Idee", "the idea", "Gute Idee!", "Good idea! Plural: die Ideen"),
    (432, "die Schwester", "the sister", "Meine Schwester wohnt in Bonn.", "My sister lives in Bonn. Plural: die Schwestern"),
    (434, "ruhig", "calm, quiet", "Die Straße ist ruhig.", "The street is quiet."),
    (437, "spät", "late", "Es ist schon spät.", "It is already late."),
    (438, "ziemlich", "quite, fairly", "Das Buch ist ziemlich dick.", "The book is quite thick."),
    (442, "kurz", "short", "Der Weg ist kurz.", "The way is short."),
    (446, "suchen", "to look for", "Ich suche meine Brille.", "I am looking for my glasses."),
    (450, "lang", "long", "Der Fluss ist lang.", "The river is long."),
    (451, "der Job", "the job", "Er hat einen neuen Job.", "He has a new job. Plural: die Jobs"),
    (455, "verstehen", "to understand", "Ich verstehe dich nicht.", "I do not understand you."),
    (456, "spielen", "to play", "Die Kinder spielen draußen.", "The children are playing outside."),
    (462, "groß", "big, tall", "Berlin ist eine große Stadt.", "Berlin is a big city."),
    (463, "die Hand", "the hand", "Gib mir deine Hand.", "Give me your hand. Plural: die Hände"),
    (464, "der Grund", "the reason", "Was ist der Grund?", "What is the reason? Plural: die Gründe"),
    (467, "die Mama", "the mum", "Mama, ich habe Hunger.", "Mum, I am hungry."),
    (471, "die Stunde", "the hour", "Der Film dauert zwei Stunden.", "The film lasts two hours. Plural: die Stunden"),
    (472, "hoffen", "to hope", "Ich hoffe, du kommst.", "I hope you are coming."),
    (474, "oben", "up, upstairs", "Das Bad ist oben.", "The bathroom is upstairs."),
    (475, "gestern", "yesterday", "Gestern war Sonntag.", "Yesterday was Sunday."),
    (476, "versuchen", "to try", "Ich versuche es noch einmal.", "I will try again."),
    (480, "endlich", "finally", "Endlich ist Wochenende.", "It is finally the weekend."),
    (486, "schwer", "heavy, difficult", "Die Tasche ist schwer.", "The bag is heavy."),
    (487, "anders", "different, differently", "Hier ist alles anders.", "Everything is different here."),
    (490, "fünf", "five", "Ich habe fünf Euro.", "I have five euros."),
    (491, "das Wasser", "the water", "Das Wasser ist warm.", "The water is warm."),
    (493, "erste", "first", "Das ist mein erster Tag.", "This is my first day."),
    (496, "die Geschichte", "the story, the history", "Erzähl mir eine Geschichte.", "Tell me a story. Plural: die Geschichten"),
    (498, "holen", "to fetch, to get", "Ich hole Brötchen.", "I am getting bread rolls."),
    (499, "bedeuten", "to mean", "Was bedeutet dieses Wort?", "What does this word mean?"),
    (500, "nett", "nice, kind", "Der Nachbar ist nett.", "The neighbour is nice."),
    (501, "die Wahrheit", "the truth", "Sag mir die Wahrheit.", "Tell me the truth."),
    (502, "die Woche", "the week", "Nächste Woche habe ich Urlaub.", "Next week I am on holiday. Plural: die Wochen"),
    (506, "bestimmt", "certainly, definitely", "Er kommt bestimmt.", "He will definitely come."),
    (507, "hoch", "high", "Der Berg ist hoch.", "The mountain is high."),
    (508, "das Alter", "the age", "In deinem Alter war ich klein.", "At your age I was small. alt: old"),
    (512, "das Land", "the country, the land", "Deutschland ist ein großes Land.", "Germany is a big country. Plural: die Länder"),
    (513, "das Zimmer", "the room", "Mein Zimmer ist hell.", "My room is bright. Plural: die Zimmer"),
    (517, "der Spaß", "the fun", "Das macht Spaß.", "That is fun."),
    (519, "die Schuld", "the guilt, the fault", "Das ist nicht meine Schuld.", "That is not my fault."),
    (522, "verlassen", "to leave", "Sie verlässt das Haus um acht.", "She leaves the house at eight. du verlässt"),
    (523, "zeigen", "to show", "Zeig mir das Foto.", "Show me the photo."),
    (524, "beste", "best", "Das ist mein bester Freund.", "That is my best friend."),
    (525, "ernst", "serious", "Das ist ein ernstes Problem.", "That is a serious problem."),
    (528, "der Ort", "the place", "Das ist ein schöner Ort.", "This is a beautiful place. Plural: die Orte"),
    (531, "manchmal", "sometimes", "Manchmal koche ich.", "Sometimes I cook."),
    (533, "die Seite", "the page, the side", "Lies Seite zehn.", "Read page ten. Plural: die Seiten"),
    (538, "das Spiel", "the game", "Das Spiel beginnt um drei.", "The game starts at three. Plural: die Spiele"),
    (542, "die Chance", "the chance", "Das ist deine Chance.", "This is your chance. Plural: die Chancen"),
    (543, "die Freundin", "the friend (female), the girlfriend", "Meine Freundin heißt Lena.", "My girlfriend is called Lena. Plural: die Freundinnen"),
    (545, "gefallen", "to be pleasing, to like", "Das Bild gefällt mir.", "I like the picture. Literally: the picture pleases me"),
    (547, "erzählen", "to tell", "Erzähl mir von deinem Tag.", "Tell me about your day."),
    (550, "entschuldigen", "to excuse", "Entschuldigen Sie, wo ist der Bahnhof?", "Excuse me, where is the station?"),
    (551, "wichtig", "important", "Das ist sehr wichtig.", "That is very important."),
    (554, "das Bett", "the bed", "Ich gehe ins Bett.", "I am going to bed. Plural: die Betten"),
    (556, "die Sache", "the thing, the matter", "Das ist eine andere Sache.", "That is another matter. Plural: die Sachen"),
    (558, "schlecht", "bad", "Das Wetter ist schlecht.", "The weather is bad."),
    (559, "die Schule", "the school", "Die Schule beginnt um acht.", "School starts at eight. Plural: die Schulen"),
    (560, "die Entschuldigung", "the apology, excuse me", "Entschuldigung, ist hier frei?", "Excuse me, is this seat free? Plural: die Entschuldigungen"),
    (561, "das Wort", "the word", "Das Wort ist neu für mich.", "The word is new to me. Plural: die Wörter"),
    (566, "schlafen", "to sleep", "Ich schlafe acht Stunden.", "I sleep eight hours. du schläfst, er schläft"),
    (571, "das Gesicht", "the face", "Ihr Gesicht ist rot.", "Her face is red. Plural: die Gesichter"),
    (575, "unten", "down, downstairs", "Die Küche ist unten.", "The kitchen is downstairs."),
    (576, "der Teil", "the part", "Der erste Teil ist leicht.", "The first part is easy. Plural: die Teile"),
    (580, "stellen", "to put, to place", "Stell die Vase auf den Tisch.", "Put the vase on the table."),
    (581, "oft", "often", "Ich fahre oft Rad.", "I often ride a bike."),
    (585, "trinken", "to drink", "Was möchtest du trinken?", "What would you like to drink?"),
    (592, "ehrlich", "honest", "Sei ehrlich.", "Be honest."),
    (593, "die Eltern", "the parents", "Meine Eltern wohnen in München.", "My parents live in Munich. Plural only"),
    (595, "das Herz", "the heart", "Mein Herz schlägt schnell.", "My heart is beating fast. Plural: die Herzen"),
    (597, "glücklich", "happy", "Ich bin sehr glücklich.", "I am very happy."),
    (599, "alt", "old", "Wie alt bist du?", "How old are you?"),
    (601, "auf Wiedersehen", "goodbye", "Auf Wiedersehen, bis Montag.", "Goodbye, see you Monday."),
    (602, "frei", "free", "Ist der Platz frei?", "Is this seat free?"),
    (605, "möglich", "possible", "Das ist nicht möglich.", "That is not possible."),
    (614, "der Platz", "the place, the seat, the square", "Ist hier noch ein Platz frei?", "Is there a free seat here? Plural: die Plätze"),
    (617, "der Papa", "the dad", "Papa kocht heute.", "Dad is cooking today."),
    (618, "falsch", "wrong, false", "Die Antwort ist falsch.", "The answer is wrong."),
    (621, "die Nummer", "the number", "Wie ist deine Nummer?", "What is your number? Plural: die Nummern"),
    (622, "früher", "earlier, in the past", "Früher wohnte ich in Kiel.", "I used to live in Kiel."),
    (624, "wohin", "where to", "Wohin fährst du?", "Where are you going?"),
    (626, "früh", "early", "Ich stehe früh auf.", "I get up early."),
    (627, "setzen", "to set, to sit down (sich)", "Setz dich bitte.", "Please sit down."),
    (628, "zuerst", "first, at first", "Zuerst frühstücken wir.", "First we have breakfast."),
    (629, "wahrscheinlich", "probably", "Es wird wahrscheinlich regnen.", "It will probably rain."),
    (633, "das Telefon", "the telephone", "Das Telefon klingelt.", "The telephone is ringing. Plural: die Telefone"),
    (636, "willkommen", "welcome", "Willkommen in Berlin!", "Welcome to Berlin!"),
    (637, "der Plan", "the plan", "Hast du einen Plan?", "Do you have a plan? Plural: die Pläne"),
    (639, "retten", "to save, to rescue", "Der Arzt rettet Leben.", "The doctor saves lives."),
    (643, "der Fehler", "the mistake", "Das war mein Fehler.", "That was my mistake. Plural: die Fehler"),
    (646, "zehn", "ten", "Ich habe zehn Finger.", "I have ten fingers."),
    (649, "nächste", "next", "Die nächste Straße links.", "The next street on the left."),
    (654, "langsam", "slow, slowly", "Sprich bitte langsam.", "Please speak slowly."),
    (657, "sechs", "six", "Der Laden öffnet um sechs.", "The shop opens at six."),
    (660, "das Büro", "the office", "Ich arbeite im Büro.", "I work in the office. Plural: die Büros"),
    (665, "schaffen", "to manage, to accomplish", "Wir schaffen das.", "We can do it."),
    (666, "leider", "unfortunately", "Leider habe ich keine Zeit.", "Unfortunately I have no time."),
    (669, "trotzdem", "nevertheless", "Es regnet, trotzdem gehe ich raus.", "It is raining, but I am going out anyway."),
    (670, "der Doktor", "the doctor", "Der Doktor kommt gleich.", "The doctor is coming shortly. Plural: die Doktoren"),
    (673, "voll", "full", "Der Bus ist voll.", "The bus is full."),
    (674, "der Film", "the film", "Der Film war lang.", "The film was long. Plural: die Filme"),
    (675, "überall", "everywhere", "Überall liegt Schnee.", "There is snow everywhere."),
    (679, "direkt", "direct, directly", "Der Zug fährt direkt nach Paris.", "The train goes directly to Paris."),
    (687, "danach", "afterwards", "Danach gehen wir essen.", "Afterwards we go out to eat."),
    (688, "funktionieren", "to work, to function", "Der Drucker funktioniert nicht.", "The printer does not work."),
    (692, "lernen", "to learn", "Ich lerne Deutsch.", "I am learning German."),
    (695, "nennen", "to call, to name", "Alle nennen mich Tom.", "Everyone calls me Tom."),
    (698, "das Feuer", "the fire", "Das Feuer ist warm.", "The fire is warm. Plural: die Feuer"),
    (699, "laufen", "to run, to walk", "Wir laufen zum Park.", "We walk to the park. du läufst, er läuft"),
    (701, "erinnern", "to remember (sich)", "Ich erinnere mich an den Tag.", "I remember the day."),
    (707, "verlieren", "to lose", "Ich verliere oft meine Schlüssel.", "I often lose my keys."),
    (709, "der Kaffee", "the coffee", "Ich trinke Kaffee mit Milch.", "I drink coffee with milk."),
    (710, "die Luft", "the air", "Die Luft ist frisch.", "The air is fresh."),
    (714, "ziehen", "to pull, to move house", "Wir ziehen nach Berlin.", "We are moving to Berlin."),
    (715, "verschwinden", "to disappear", "Der Hund ist verschwunden.", "The dog has disappeared."),
    (717, "aufhören", "to stop", "Hör auf zu reden.", "Stop talking."),
    (722, "die Hoffnung", "the hope", "Es gibt noch Hoffnung.", "There is still hope. Plural: die Hoffnungen"),
    (727, "das Buch", "the book", "Das Buch ist spannend.", "The book is exciting. Plural: die Bücher"),
    (728, "krank", "ill, sick", "Ich bin krank.", "I am ill."),
    (732, "der Arzt", "the doctor (medical)", "Ich gehe zum Arzt.", "I am going to the doctor. Plural: die Ärzte"),
    (733, "froh", "glad", "Ich bin froh, dass du da bist.", "I am glad you are here."),
    (735, "die Straße", "the street", "Die Straße ist lang.", "The street is long. Plural: die Straßen"),
    (736, "rufen", "to call, to shout", "Ruf mich morgen an.", "Call me tomorrow. anrufen: to phone"),
    (737, "heiraten", "to marry", "Sie heiraten im Mai.", "They are getting married in May."),
    (740, "super", "great, super", "Das ist super!", "That is great!"),
    (742, "der Onkel", "the uncle", "Mein Onkel wohnt in Bern.", "My uncle lives in Bern. Plural: die Onkel"),
    (745, "die Party", "the party", "Die Party ist am Samstag.", "The party is on Saturday. Plural: die Partys"),
    (746, "erklären", "to explain", "Kannst du das erklären?", "Can you explain that?"),
    (749, "vertrauen", "to trust", "Ich vertraue dir.", "I trust you."),
    (752, "leicht", "easy, light", "Die Aufgabe ist leicht.", "The task is easy."),
    (755, "das Gefühl", "the feeling", "Ich habe ein gutes Gefühl.", "I have a good feeling. Plural: die Gefühle"),
    (756, "kaufen", "to buy", "Ich kaufe Brot.", "I am buying bread."),
    (760, "die Zukunft", "the future", "Die Zukunft ist unklar.", "The future is unclear."),
    (761, "weniger", "less, fewer", "Ich esse weniger Zucker.", "I eat less sugar."),
    (763, "das Licht", "the light", "Mach das Licht an.", "Turn the light on. Plural: die Lichter"),
    (765, "der Himmel", "the sky, the heaven", "Der Himmel ist blau.", "The sky is blue."),
    (766, "die Nachricht", "the message, the news", "Ich habe eine Nachricht für dich.", "I have a message for you. Plural: die Nachrichten"),
    (769, "kümmern", "to take care of (sich)", "Ich kümmere mich um die Katze.", "I take care of the cat."),
    (770, "laut", "loud", "Die Musik ist zu laut.", "The music is too loud."),
    (773, "die Erde", "the earth", "Die Erde ist rund.", "The earth is round."),
    (775, "der Schlüssel", "the key", "Wo ist der Schlüssel?", "Where is the key? Plural: die Schlüssel"),
    (782, "der Körper", "the body", "Sport ist gut für den Körper.", "Sport is good for the body. Plural: die Körper"),
    (786, "schreiben", "to write", "Ich schreibe einen Brief.", "I am writing a letter."),
    (787, "böse", "angry, evil", "Sei nicht böse.", "Do not be angry."),
    (790, "die Katze", "the cat", "Die Katze schläft.", "The cat is sleeping. Plural: die Katzen"),
    (792, "der Hund", "the dog", "Der Hund bellt.", "The dog barks. Plural: die Hunde"),
    (795, "der Brief", "the letter", "Der Brief ist für dich.", "The letter is for you. Plural: die Briefe"),
    (797, "die Milch", "the milk", "Die Milch ist im Kühlschrank.", "The milk is in the fridge."),
    (800, "das Wetter", "the weather", "Das Wetter ist schön.", "The weather is nice."),
]

OUT = Path(__file__).with_name("german-a1.csv")


def main() -> None:
    fronts = [c[1] for c in CARDS]
    dupes = {f for f in fronts if fronts.count(f) > 1}
    assert not dupes, f"duplicate fronts: {dupes}"
    assert len(CARDS) == 300, f"expected 300 cards, have {len(CARDS)}"
    for rank, front, back, example, note in CARDS:
        assert front and back and example, (rank, front)
    with OUT.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["front", "back", "example", "note"])
        for _, front, back, example, note in CARDS:
            w.writerow([front, back, example, note])
    print(f"wrote {OUT} with {len(CARDS)} cards")


if __name__ == "__main__":
    main()
