import numpy as np
import pandas as pd
import pytest
import torch

from features import PAPER_FEATURES
from train import HalfLifeRegression, Tensors, fit, predict, to_tensors


def _synthetic(n: int = 20000, seed: int = 0) -> tuple[pd.DataFrame, np.ndarray]:
    """Rows whose p is generated by a known theta, so training should recover it."""
    rng = np.random.default_rng(seed)
    seen = rng.integers(1, 30, n)
    correct = np.minimum(seen, rng.binomial(seen, 0.85))
    delta = rng.uniform(0.1, 20, n)
    theta = np.array([-0.5, 0.9, -0.6])  # bias, sqrt_correct, sqrt_wrong
    x = np.column_stack([np.ones(n), np.sqrt(1 + correct), np.sqrt(1 + seen - correct)])
    h = 2 ** (x @ theta)
    p = 2 ** (-delta / h)
    df = pd.DataFrame(
        {
            "history_seen": seen,
            "history_correct": correct,
            "delta": delta * 86400,
            "p_recall": p,
            "session_seen": 1,
            "lexeme_id": pd.Categorical(["l"] * n),
        }
    )
    return df, theta


def test_recovers_known_weights_without_lexemes():
    df, theta = _synthetic()
    t = to_tensors(df, list(PAPER_FEATURES), lexeme_term=False)
    model = HalfLifeRegression(3, 0)
    cfg = dict(
        seed=0,
        epochs=30,
        batch_size=512,
        learning_rate=0.02,
        l2=0.0,
        lexeme_l2=0.0,
        half_life_loss_weight=0.0,
    )
    fit(model, t, cfg, log=lambda _: None)
    np.testing.assert_allclose(model.theta.detach().numpy(), theta, atol=0.1)
    p_hat, h_hat = predict(model, t)
    assert np.mean(np.abs(p_hat - t.p.numpy())) < 0.02


def test_predictions_match_the_closed_form():
    model = HalfLifeRegression(3, 2)
    with torch.no_grad():
        model.theta.copy_(torch.tensor([1.0, 0.5, -0.25]))
        model.lexeme.weight.copy_(torch.tensor([[0.0], [1.0]]))
    x = torch.tensor([[1.0, 2.0, 1.0]])
    delta = torch.tensor([4.0])
    p0, h0 = model(x, torch.tensor([0]), delta)
    p1, h1 = model(x, torch.tensor([1]), delta)
    assert h0.item() == pytest.approx(2 ** (1.0 + 1.0 - 0.25), rel=1e-6)
    assert h1.item() == pytest.approx(2 * h0.item(), rel=1e-6)
    assert p0.item() == pytest.approx(2 ** (-4.0 / h0.item()), rel=1e-6)
    assert p1.item() == pytest.approx(2 ** (-4.0 / h1.item()), rel=1e-6)


def test_tensors_shapes():
    df, _ = _synthetic(100)
    t = to_tensors(df, list(PAPER_FEATURES), lexeme_term=True)
    assert isinstance(t, Tensors)
    assert t.x.shape == (100, 3) and t.lex.shape == (100,) and t.h.shape == (100,)
